### ISSUE TITLE
Whatsapp sending issue

### ISSUE THREAD

**Issue by biplob86429** [satish603/Whatsapp_API#1]
When i try this method Whatsapp not send
Sending Messages POST : /chat/sendmessage/<phone_number>

Please tell me what i have to modify in below code. also if i want to use get method how it can be process ?

app.get("/testapi", (req, res, next) => {
    axios.post('http://localhost:5000/chat/sendmessage/91123456', {// ph number wih your country code.91 here indicates for india
    message: 'hello world from heroku docker',})
    .then(function (response) {
      res.send("Message sent to the user")
      console.log(response);
    })
    .catch(function (error) {
      res.send("Error Message not sent")
      console.log(error);
    });
    });

**Comment by satish603** [comment]
Please try these steps and reply.

- npm install --force
- npm start
![image](https://user-images.githubusercontent.com/60779510/131778043-0fb860ea-3332-43f6-bac5-99d151f725e4.png)
check server is running
### Then scan the QR code with your WhatsApp application by visiting 
- http://localhost:5000/auth/getqr
### Check for successful connection 
- http://localhost:5000/auth/checkauth
IF connected successfully you can see the same results
![image](https://user-images.githubusercontent.com/60779510/131778452-04df7675-7857-49db-8a39-c65fde7b2382.png)

**Comment by biplob86429** [comment]
Sir,
Connection is successful. 
But how i can send Whatsapp message to a number by Get or post method by postman ?
Here you set a fixed number. i want to dynamic it.
Please  help me

**Comment by satish603** [comment]
Yes, you can do it's possible and easy. Let me show using postman.
![image](https://user-images.githubusercontent.com/60779510/131779881-45e8b801-8b7e-4d2f-92c2-008081631e5e.png)

**Comment by biplob86429** [comment]
Sir,
I have to change anything in index.js ?

app.get("/testapi", (req, res, next) => {
    axios.post('http://localhost:5000/chat/sendmessage/91123456789', {// ph number wih your country code.91 here indicates for india
    message: 'hello world from heroku docker',})
    .then(function (response) {
      res.send("Message sent to the user")
      console.log(response);
    })
    .catch(function (error) {
      res.send("Error Message not sent")
      console.log(error);
    });
    });

becouse wehen i submit from Postman et showing - 

{
    "status": "error",
    "message": "please enter valid phone and message"
}

**Comment by satish603** [comment]
no, you don't have to change any of the code. The application is already in a dynamic state.
please provide a screenshot if possible.
because it's working totally fine here I had verified just now
![image](https://user-images.githubusercontent.com/60779510/131781144-c0f991b4-29cd-4de3-8f39-cb7b6d961ad9.png)

**Comment by biplob86429** [comment]
![image](https://user-images.githubusercontent.com/76605661/131782282-695c7ba1-a56e-4a54-81ed-ea4bf1676a09.png)

**Comment by satish603** [comment]
![1](https://user-images.githubusercontent.com/60779510/131782700-c577a7ff-d43f-4769-89f1-5e3a64d7a218.png)
hope this works fine.

**Comment by biplob86429** [comment]
Great Sir. Thank you for your Support. you are great sir.

Can you guide how can we set Token validation in Send message api url ?

**Comment by satish603** [comment]
You are welcome! 
I am not familiar with Token validation. Hope you learn soon and guide me.😂
Happy coding😎
