### ISSUE TITLE
Webook Not working

### ISSUE THREAD

**Issue by biplob86429** [satish603/Whatsapp_API#2]
{
    "port":5000,
    "webhook":{
        "enabled":true,
        "path":"http://yourdomain.com/callback/whatsappbot"
    }
}

But when incoming whatsapp received its showing in console but no call back hit to webhook.
Please check and guide us

**Comment by satish603** [comment]
This project is not configured for web-hooks if you wish to add this feature 
fork this project and 
npm install node-webhooks --save
and follow the official document [https://www.npmjs.com/package/node-webhooks](https://www.npmjs.com/package/node-webhooks)
