### ISSUE TITLE
Please help for student

### ISSUE THREAD

**Issue by isenorev** [satish603/Whatsapp_API#4]
Hello goodnight!

I'm a beginner programming student, I loved this project but I'm having difficulties processing the sending and returning of the api on the front-end.

Could you help me with some simple html example with message sending and request return? Please!!

**Comment by satish603** [comment]
you can refer to [](https://github.com/satish603/online-whatsapp-msg) for sending msg using HTML.

**Comment by satish603** [comment]
you can refer to [https://github.com/satish603/online-whatsapp-msg](url) for sending msg using html

**Comment by satish603** [comment]
Whatsapp api is live now
